all: build/V207.pdf

# hier Python-Skripte:
build/grosse_kugel_temperature.pdf: plot.py ../matplotlibrc ../header-matplotlib.tex | build
	# so that matplotlib can find the tex header when running
	# LaTeX in the tmp directory
	# and set the matplotlibrc
	TEXINPUTS=$$(pwd)/..: MATPLOTLIBRC=../matplotlibrc conda run -n praktikum python plot.py

# hier weitere Abhängigkeiten für build/vXXX.pdf deklarieren:
build/V207.pdf: build/grosse_kugel_temperature.pdf plot.py

build/V207.pdf: FORCE | build
	# to find header and bib files in the main directory
	TEXINPUTS=..: \
	BIBINPUTS=..: \
	max_print_line=1048576 \
	latexmk \
	  --lualatex \
	  --output-directory=build \
	  --interaction=nonstopmode \
	  --halt-on-error \
	V207.tex

build:
	mkdir -p build

clean:
	rm -rf build

FORCE:

.PHONY: all clean
